ぷるりく
jaoafa/MyMaid4 pull request #42
Opened 2021-03-23 13:00 UTC by jojo3926

勢いでつくってしまった
作ったら全部作らなければならなくなったので.........

2021-03-23 13:09 UTC, book000 commented
これ動作チェックしましたか…？クラス名からしてアウトなんですけど

2021-03-23 13:50 UTC, book000 commented
distanceが300以上の場合の処理は作らない感じですか

2021-03-23 13:51 UTC, book000 requested changes

2021-03-23 13:51 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/AntiProblemCommand.java
> +public class AntiProblemCommand extends MyMaidLibrary implements Listener {
```markdown
- 全てのイベント駆動の機能は src/main/java/com/jaoafa/mymaid4/event/Event_<FuncName>.java に配置されます。
```
https://github.com/jaoafa/MyMaid4/blob/master/CONTRIBUTING.md

2021-03-23 13:51 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/AntiProblemCommand.java
> +                //MyMaidLibrary.checkSpam(player);
謎のコメント

2021-03-23 13:51 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/AntiProblemCommand.java
> +                    if (!parser.getArgs().containsKey("r")) {
1.16.5用にdistanceで判断するべきでしょう。~~とはいえ、1.13.xだかでセレクターの仕組みが変わったのでうまくパーサーが動作しなくなると思います~~

2021-03-23 13:51 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/AntiProblemCommand.java
> +                    if (!parser.getArgs().containsKey("r")) {
~~正直、これはかなり解決の難易度高めだと思います
ですので別タスクとしてIssue立てて将来的に対応でもいいです~~

2021-03-23 13:51 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/MyMaidConfig.java
> -    public void init(){
なんでinitが移動しているんだろう…

2021-03-23 13:51 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/MyMaidConfig.java
> +    private static final Map<UUID, Integer> SpamCount = new HashMap<>();
これらは `config.yml` で定義されるデータではないため、 `MyMaidData` で定義される必要があります。

2021-03-23 13:51 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/MyMaidConfig.java
> +    public static Integer getSpamCount(UUID uuid) {
これらは `config.yml` で定義されるデータではないため、`MyMaidData` で定義される必要があります。

2021-03-23 13:51 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
> +     * @param player [player's name]
`@param player Player's Name`

2021-03-23 13:51 UTC, book000 commented
@yuuahp お試しでレビューしてみたければしてみてください。したくないならそのままでもよし

2021-03-23 16:51 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/MyMaidConfig.java
> +    private static final Map<UUID, Integer> SpamCount = new HashMap<>();
また、これらの変数が `Event_AntiProblemCommand` クラスでしか使用されないのであれば、`Event_AntiProblemCommand` クラスへ `static` で実装するべきです。

2021-03-23 22:24 UTC, yuuahp reviewed
3週くらい読んだんですがifがまとめられるんじゃないかくらいしかわかりませんでした

2021-03-23 22:24 UTC, yuuahp commented on src/main/java/com/jaoafa/mymaid4/lib/SelectorParser.java
> +            if (!isInt(args.get("x"))) {
`if (args.containsKey("x")&&!isInt(args.get("x"))) {`
にまとめられると思います

2021-03-23 22:24 UTC, yuuahp commented on src/main/java/com/jaoafa/mymaid4/lib/SelectorParser.java
> +            if (!isInt(args.get("y"))) {
`if (args.containsKey("y")&&!isInt(args.get("y"))) {`
にまとめられると思います

2021-03-23 22:24 UTC, yuuahp commented on src/main/java/com/jaoafa/mymaid4/lib/SelectorParser.java
> +            if (!isInt(args.get("z"))) {
`if (args.containsKey("z")&&!isInt(args.get("z"))) {`
にまとめられると思います

2021-03-23 22:24 UTC, yuuahp commented on src/main/java/com/jaoafa/mymaid4/lib/SelectorParser.java
> +            if (!isInt(args.get("distance"))) {
`if (args.containsKey("distance")&&!isInt(args.get("distance"))) {`
にまとめられると思います

2021-03-24 02:33 UTC, book000 commented
というわけで、修正お願いします。

2021-03-25 01:53 UTC, book000 commented
`static String[] LeastOne = new String[]{"r", "type", "team", "name"};` だけこちらで直しました。ローカルにプルしてください

それ以外、ゆうあ氏レビュー内容が修正されればマージします。

2021-03-26 04:32 UTC, book000 commented
本当ならコンフリクトも直してほしいですけど…まあいいや直します

2021-03-26 04:45 UTC, book000 approved these changes

2021-03-26 04:46 UTC, book000 commented
あかんコンフリクト改善で失敗した

2021-03-26 04:48 UTC, book000 approved these changes

2021-03-26 04:50 UTC, book000 approved these changes

2021-03-26 04:50 UTC, book000 commented
三度目の正直

2021-03-26 04:53 UTC, merged