wireコマンド修正。コウモリの透明化エフェクト永続化やワイヤーの出現位置の調整など
jaoafa/MyMaid4 pull request #447
Opened 2021-06-05 18:44 UTC by kohonayoshi

## 実装・修正した内容の簡単な解説

> どのような機能・コマンドを実装したり、修正したかを簡潔に説明してください

・コウモリの透明化エフェクトが消えても再度透明化エフェクトが自動で付くように。
・ワイヤーの出現位置を調整し、ワイヤーの端がブロックの中心に来るように。
・コウモリに付くタグをwireUnitからCmdWire1,CmdWire2へ変更。
・撤去したリードの本数をカウントしてたけど色々いじってたら上手くカウントされなくなって面倒なので消去しました。
・その他文章の修正など

## 関連する Issue

> 関連する Issue がある場合は、`#1` のような形式で示してください
> マージと同時にクローズされる必要がある場合は、`close #1` のように記載してください

## チェックリスト

> `[ ]` を `[x]` にすることでチェックできます

- [x] 【必須】[CONTRIBUTING](https://github.com/jaoafa/MyMaid4/blob/master/CONTRIBUTING.md) を読みました
- [x] 【必須】テストサーバで動作確認をしました
  - [x] ローカルサーバで動作確認しました
  - [x] ZakuroHatのテストサーバで動作確認しました
- [x] 【必須】プロジェクトのコードスタイルに適合しています（IDEAのコミット前処理でフォーマットして下さい）
- [x] 【必須】`NULL` が返却されるかもしれない(`@Nullable`)メソッドや変数は NULL チェックを実装しました
- [ ] 非推奨とされているメソッド・クラスなどを使用していません（なるべく推奨されるメソッドなどに置き換える）
  - [ ] 代替メソッド・クラスなどがないため、非推奨メソッドなどを使用しています
- [ ] 複数のクラスにわたって使用される変数があるので、 `MyMaidData` にその変数を作成し管理しています
- [ ] 複数のクラスにわたって多く使用される関数があるので、 `MyMaidLibrary` にその関数を作成し管理しています

## 追加情報

> 何か追加情報がある場合は記載してください

2021-06-05 19:45 UTC, book000 requested changes

2021-06-05 19:45 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java
> +        Location loc2 = new Location(player.getWorld(), locationArgumentPos2.getX() + 0.5, locationArgumentPos2.getY() + 0.0375, locationArgumentPos2.getZ() + 0.5 - 0.2);
```suggestion
        Location loc2 = new Location(player.getWorld(), locationArgumentPos2.getX() + 0.5, locationArgumentPos2.getY() + 0.0375, locationArgumentPos2.getZ() + 0.3);
```
このようにしない理由は何故ですか？

2021-06-05 19:45 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java
> +            Location loc2 = new Location(player.getWorld(), locationArgumentWePos2.getX() + 0.5, locationArgumentWePos2.getY() + 0.0375, locationArgumentWePos2.getZ() + 0.5 - 0.2);
```suggestion
            Location loc2 = new Location(player.getWorld(), locationArgumentWePos2.getX() + 0.5, locationArgumentWePos2.getY() + 0.0375, locationArgumentWePos2.getZ() + 0.3);
```
134行目と同じ

2021-06-05 19:45 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java
> +                Location loc2 = new Location(player.getWorld(), polylist.get(i + 1).getX() + 0.5, polyPosY + 0.0375, polylist.get(i + 1).getZ() + 0.5 - 0.2);
```suggestion
                Location loc2 = new Location(player.getWorld(), polylist.get(i + 1).getX() + 0.5, polyPosY + 0.0375, polylist.get(i + 1).getZ() + 0.3);
```

2021-06-05 19:45 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java
> +                Location loc2 = new Location(player.getWorld(), polylist.get(i + 1).getX() + 0.5, polyPosY + 0.0375, polylist.get(i + 1).getZ() + 0.5 - 0.2);
```suggestion
                Location loc2 = new Location(player.getWorld(), polylist.get(i + 1).getX() + 0.5, polyPosY + 0.0375, polylist.get(i + 1).getZ() + 0.3);
```

2021-06-05 19:45 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java
> +        Location loc2 = new Location(player.getWorld(), locationArgumentPos2.getX() + 0.5, locationArgumentPos2.getY() + 0.0375, locationArgumentPos2.getZ() + 0.5 - 0.2);
```suggestion
        Location loc2 = new Location(player.getWorld(), locationArgumentPos2.getX() + 0.5, locationArgumentPos2.getY() + 0.0375, locationArgumentPos2.getZ() + 0.3);
```

2021-06-05 19:45 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java
> +                Location loc2 = new Location(player.getWorld(), polylist.get(i + 1).getX() + 0.5, polyPosY + 0.0375, polylist.get(i + 1).getZ() + 0.5 - 0.2);
```suggestion
                Location loc2 = new Location(player.getWorld(), polylist.get(i + 1).getX() + 0.5, polyPosY + 0.0375, polylist.get(i + 1).getZ() + 0.3);
```

2021-06-05 19:45 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            event.getCause() != EntityPotionEffectEvent.Cause.valueOf("EXPIRATION") ||
```suggestion
            event.getCause() != EntityPotionEffectEvent.Cause.EXPIRATION ||
```

2021-06-05 19:45 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            event.getModifiedType() != PotionEffectType.getByName("INVISIBILITY") ||
```suggestion
            event.getModifiedType() != PotionEffectType.INVISIBILITY ||
```

2021-06-05 19:45 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            !(ent.getScoreboardTags().contains("CmdWire1")) || !(ent.getScoreboardTags().contains("CmdWire2"))) {
```suggestion
            !ent.getScoreboardTags().contains("CmdWire1") ||
            !ent.getScoreboardTags().contains("CmdWire2")) {
```

ifを改行する場合は条件をorまたはand毎に改行した方が分かりやすいです

2021-06-05 19:45 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +public class Event_AntiDisableInvisibilityWire extends MyMaidLibrary implements Listener, EventPremise {
このクラス名だと「ワイヤーの透明化が無効化されることを非難・規制する」の意味合いになりませんか…？無効化するというより、透明化持続という意味合いにおいて `Event_InvisibilityWireContinuation` とかが妥当なようにも思うのですが、いかがでしょう

2021-06-05 19:45 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +        livent.addPotionEffect(new PotionEffect(PotionEffectType.INVISIBILITY, Integer.MAX_VALUE, 1, true, false, true));
イベントをキャンセルせずに透明化を継続している理由はありますか？挙動を把握していないので、ここでイベントをキャンセルするのと再度付与するのとでどう変わるのか不明ではありますが…。

2021-06-05 19:45 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiKillWire.java
> +            !(ent.getScoreboardTags().contains("CmdWire1") || ent.getScoreboardTags().contains("CmdWire2"))) {
```suggestion
            !ent.getScoreboardTags().contains("CmdWire1") || 
            !ent.getScoreboardTags().contains("CmdWire2")) {
```

2021-06-05 19:46 UTC, book000 commented
ちょっと私自身レビューとしてイマイチな点もあるので、もしそうしている理由があるなら説明して頂けるとより理解しやすいです

2021-06-06 03:49 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +        livent.addPotionEffect(new PotionEffect(PotionEffectType.INVISIBILITY, Integer.MAX_VALUE, 1, true, false, true));
キャンセルしようがしまいが変わらないからです(キャンセルイベントの時点で効果時間が0秒ですがさらに減算してオーバーフローして効果時間が2147483647になるとかはないです)
あと万が一透明化の付与に失敗した場合画像みたいに毎tickキャンセルイベントが発生するので危険危険危険
![image](https://user-images.githubusercontent.com/52349485/120911877-a3915600-c6c5-11eb-94e1-4cdae7760203.png)

2021-06-06 03:51 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +        livent.addPotionEffect(new PotionEffect(PotionEffectType.INVISIBILITY, Integer.MAX_VALUE, 1, true, false, true));
うーむ…付与時にキャンセルするくらいしかこのイベントはキャンセルの意味ないんですね…とりあえず解決済みとしてこれはResolveします

2021-06-06 04:07 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java
> +        Location loc2 = new Location(player.getWorld(), locationArgumentPos2.getX() + 0.5, locationArgumentPos2.getY() + 0.0375, locationArgumentPos2.getZ() + 0.5 - 0.2);
位置を再度調整していることを分かりやすくするためです(+0.3でも良いですが、他の人が見た時に理解しやすくするためです)
![image](https://user-images.githubusercontent.com/52349485/120912167-0388fc00-c6c8-11eb-956a-ea56d99e9965.png)

2021-06-06 04:08 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java
> +            Location loc2 = new Location(player.getWorld(), locationArgumentWePos2.getX() + 0.5, locationArgumentWePos2.getY() + 0.0375, locationArgumentWePos2.getZ() + 0.5 - 0.2);
以下略

2021-06-06 04:08 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java
> +                Location loc2 = new Location(player.getWorld(), polylist.get(i + 1).getX() + 0.5, polyPosY + 0.0375, polylist.get(i + 1).getZ() + 0.5 - 0.2);
以下略

2021-06-06 04:08 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java
> +                Location loc2 = new Location(player.getWorld(), polylist.get(i + 1).getX() + 0.5, polyPosY + 0.0375, polylist.get(i + 1).getZ() + 0.5 - 0.2);
​

2021-06-06 04:08 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java
> +        Location loc2 = new Location(player.getWorld(), locationArgumentPos2.getX() + 0.5, locationArgumentPos2.getY() + 0.0375, locationArgumentPos2.getZ() + 0.5 - 0.2);
​

2021-06-06 04:09 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java
> +                Location loc2 = new Location(player.getWorld(), polylist.get(i + 1).getX() + 0.5, polyPosY + 0.0375, polylist.get(i + 1).getZ() + 0.5 - 0.2);
​

2021-06-06 04:09 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java
> +        Location loc2 = new Location(player.getWorld(), locationArgumentPos2.getX() + 0.5, locationArgumentPos2.getY() + 0.0375, locationArgumentPos2.getZ() + 0.5 - 0.2);
naruhodo

2021-06-06 04:14 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            event.getCause() != EntityPotionEffectEvent.Cause.valueOf("EXPIRATION") ||
正常動作が多分確認できたので修正しました。

2021-06-06 04:16 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            event.getModifiedType() != PotionEffectType.getByName("INVISIBILITY") ||
上記記載の場合意図した動作にならないようですのでこちらはこのまま維持します。
![image](https://user-images.githubusercontent.com/52349485/120912356-4eefda00-c6c9-11eb-96e7-aead9f968fab.png)

2021-06-06 04:20 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            event.getModifiedType() != PotionEffectType.getByName("INVISIBILITY") ||
そんなわけがない、と思うんだけどなあ…

staticで `INVISIBILITY` って存在するし、`getByName` でかえってくる場合もどうせ同じなのだから、むしろenumで定義されているものを採ったほうが今後papermc側の変更に対応できるだろう、とも思うんだけど

2021-06-06 04:27 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            !(ent.getScoreboardTags().contains("CmdWire1")) || !(ent.getScoreboardTags().contains("CmdWire2"))) {
そもそもコードミスってたのでこれが正解です(コードは修正しました)
```java
event.getCause() != EntityPotionEffectEvent.Cause.EXPIRATION ||
            event.getModifiedType() != PotionEffectType.getByName("INVISIBILITY") ||
            !(ent.getScoreboardTags().contains("CmdWire1") || ent.getScoreboardTags().contains("CmdWire2")))
```

2021-06-06 04:30 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            !(ent.getScoreboardTags().contains("CmdWire1")) || !(ent.getScoreboardTags().contains("CmdWire2"))) {
```java
if (ent.getType() != EntityType.BAT ||
    event.getCause() != EntityPotionEffectEvent.Cause.EXPIRATION ||
    event.getModifiedType() != PotionEffectType.getByName("INVISIBILITY") ||
    !ent.getScoreboardTags().contains("CmdWire1") || 
    !ent.getScoreboardTags().contains("CmdWire2"))
```
にしない理由は…？別にかまわんちゃかまわんけど

2021-06-06 04:31 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            !(ent.getScoreboardTags().contains("CmdWire1")) || !(ent.getScoreboardTags().contains("CmdWire2"))) {
「CmdWire1またはCmdWire2のどちらかのタグが付いている」の否定
→「CmdWire1,CmdWire2のどちらのタグも付いていない」という状況が正しい処理なので多分このままにするしか無いと思われます
やり方あったら教えて下さい

2021-06-06 04:33 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +public class Event_AntiDisableInvisibilityWire extends MyMaidLibrary implements Listener, EventPremise {
英語わからん

2021-06-06 04:35 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiKillWire.java
> +            !(ent.getScoreboardTags().contains("CmdWire1") || ent.getScoreboardTags().contains("CmdWire2"))) {
以下略

2021-06-06 04:42 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            event.getModifiedType() != PotionEffectType.getByName("INVISIBILITY") ||
```suggestion
            event.getModifiedType().equals(PotionEffectType.INVISIBILITY) ||
```
これで動作するくさいです

2021-06-06 05:04 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            event.getModifiedType() != PotionEffectType.getByName("INVISIBILITY") ||
それだと動作逆になるので`!( )`しときますね！

2021-06-06 05:05 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            event.getModifiedType() != PotionEffectType.getByName("INVISIBILITY") ||
あっ。

2021-06-06 05:17 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            !(ent.getScoreboardTags().contains("CmdWire1")) || !(ent.getScoreboardTags().contains("CmdWire2"))) {
それだと「CmdWire1のタグが付いていない または CmdWire2のタグが付いていない」場合なので
「CmdWire1,CmdWire2のタグがどちらも付いている」場合じゃないと再透明化を実行してくれんので動かない
CmdWire1はリードを付けられている側、CmdWire2はリードを持っている側に付くタグ

2021-06-06 05:20 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            !(ent.getScoreboardTags().contains("CmdWire1")) || !(ent.getScoreboardTags().contains("CmdWire2"))) {
だったら

```java
if (ent.getType() != EntityType.BAT ||
    event.getCause() != EntityPotionEffectEvent.Cause.EXPIRATION ||
    event.getModifiedType() != PotionEffectType.getByName("INVISIBILITY") ||
    !(ent.getScoreboardTags().contains("CmdWire1") && ent.getScoreboardTags().contains("CmdWire2")))
```
では？
ORだと私が示したやつと変わらんと思うんだけど。若干あたまこんがらがってるからあれ

2021-06-06 05:20 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            !(ent.getScoreboardTags().contains("CmdWire1")) || !(ent.getScoreboardTags().contains("CmdWire2"))) {
数学わからん

2021-06-06 05:22 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            !(ent.getScoreboardTags().contains("CmdWire1")) || !(ent.getScoreboardTags().contains("CmdWire2"))) {
一つのifに全部まとめること自体の可読性懸念はあるよね

2021-06-06 05:24 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            !(ent.getScoreboardTags().contains("CmdWire1")) || !(ent.getScoreboardTags().contains("CmdWire2"))) {
```java
// 簡略化のため{}なし
if(ent.getType() != EntityType.BAT) return; // コウモリではない
if(event.getCause() != EntityPotionEffectEvent.Cause.EXPIRATION) return; // 有効期限切れ原因
if(!event.getModifiedType().equals(PotionEffectType.INVISIBILITY)) return; // 透明ではない
if(!ent.getScoreboardTags().contains("CmdWire1") && !ent.getScoreboardTags().contains("CmdWire2")) return; // CmdWire1 も CmdWire2 もついてない
```

2021-06-06 05:44 UTC, kohonayoshi commented on src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java
> +            !(ent.getScoreboardTags().contains("CmdWire1")) || !(ent.getScoreboardTags().contains("CmdWire2"))) {
とりあえず上を書き方を参考にして変更しました

2021-06-06 05:50 UTC, kohonayoshi commented
@book000 とりあえず全部修正しました

2021-06-06 05:50 UTC, book000 approved these changes

2021-06-06 05:51 UTC, merged