fix: 南の楽園の場所を変更
jaoafa/MyMaid4 pull request #735
Opened 2022-03-13 12:45 UTC by yuuahp

## 実装・修正した内容の簡単な解説

> 南の楽園の場所を修正しました。

## 関連する Issue

> close #726 

## チェックリスト

> `[ ]` を `[x]` にすることでチェックできます

- [x] 【必須】[CONTRIBUTING](https://github.com/jaoafa/MyMaid4/blob/master/CONTRIBUTING.md) を読みました
- [ ] 【必須】テストサーバで動作確認をしました
    - [ ] ローカルサーバで動作確認しました
    - [ ] ZakuroHatのテストサーバで動作確認しました
- [x] 【必須】プロジェクトのコードスタイルに適合しています（IDEAのコミット前処理でフォーマットして下さい）
- [x] 【必須】`NULL` が返却されるかもしれない(`@Nullable`)メソッドや変数は NULL チェックを実装しました
- [x] 非推奨とされているメソッド・クラスなどを使用していません（なるべく推奨されるメソッドなどに置き換える）
    - [ ] 代替メソッド・クラスなどがないため、非推奨メソッドなどを使用しています
- [x] 複数のクラスにわたって使用される変数があるので、 `MyMaidData` にその変数を作成し管理しています
- [ ] 複数のクラスにわたって多く使用される関数があるので、 `MyMaidLibrary` にその関数を作成し管理しています

## 追加情報

> DBがなくてjailできないので、✞本番環境でテスト✞になってしまうかも...

2022-03-13 19:58 UTC, book000 requested changes
具体的にレビューする時間を取れなかったので、要点だけ…

- メッセージに引用符が残ってたので勝手にいじっておきました
- 開発サーバを立て直しました。そこでテストしてみてください。詳しくはdevelopmentチャンネル
- `MyMaidData.paradiseLocation` で一括管理しているのは非常によいのですが、`Jao_Afa` ワールドの存在確認がイベントケースによってまちまちなように見えます(今までもそうだったということですが)。ワールド存在確認をする/しないはどっちでも良い(原則`Jao_Afa`がないサーバで動くことはないので)のでどちらに合わせるかはお任せします。
- これもテストサーバありきな話だと思うのですが、移動可能範囲距離は多分見直す必要がある気がします。どうでしょう？

よろしくお願いします。

2022-03-13 23:25 UTC, yuuahp commented
`teleportToParadise()` 的なものを作って、そこで確認しようかと思います。

2022-03-14 13:50 UTC, book000 requested changes
Jail/EBan実施時、被処罰者の移動可能距離に関しては必要に応じて変更をお願いします。
メイン鯖入ってWEで測るくらいしかやりようないので、デプロイしたあとに修正でもおっけーです

2022-03-14 13:50 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
> +import com.avaje.ebeaninternal.server.lib.util.NotFoundException;
初めて見たパッケージのExceptionなんですけど、`server` とか含まれるあたりこれHTTP系サーバの404-Exceptionではないですかね？
そもそも [Paperのサーバでの動作テストCI](https://github.com/jaoafa/MyMaid4/runs/5537003368?check_suite_focus=true#step:6:110) もNoClassDefFoundErrorで落ちてしまっているので、`java.lang.IllegalStateException` あたりを使うのが無難な気がします。

2022-03-14 13:50 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
> +            return player.teleport(paradise,teleportCause);
コード整形をお願いします

```suggestion
            return player.teleport(paradise, teleportCause);
```

2022-03-14 13:50 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/EBan.java
> +                    MyMaidLibrary.teleportToParadise((Player) player, null);
TeleportCauseをJail/EBan適用時だけ付与するのも不自然なので、一律で `TeleportCause.PLUGIN` を渡してしまってもいいかもしれません。

```suggestion
                    MyMaidLibrary.teleportToParadise((Player) player, TeleportCause.PLUGIN);
```

2022-03-14 13:50 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/Jail.java
> +                    MyMaidLibrary.teleportToParadise((Player) player, null);
lib/EBan と同様

```suggestion
                    MyMaidLibrary.teleportToParadise((Player) player, TeleportCause.PLUGIN);
```

2022-03-15 23:34 UTC, yuuahp commented
そういえば移動可能距離って何ブロックくらい？

2022-03-15 23:36 UTC, book000 commented
> メイン鯖入ってWEで測るくらいしかやりようない

です

2022-03-16 00:04 UTC, yuuahp commented
幼児終わったら図りに行く

2022-03-16 00:04 UTC, yuuahp commented
a

2022-03-16 03:26 UTC, yuuahp commented
端から端まで行けた...
![image](https://user-images.githubusercontent.com/53546237/158510823-4aeead40-fa40-4c76-b054-eca5f25c4bbc.png)

2022-03-16 03:34 UTC, book000 commented
ん？？！？！

移動制約は以下のあたりで制限していて、PlayerMoveあたりで検知してるはずなんだけども…？
https://github.com/jaoafa/MyMaid4/blob/ffb32875f038b4252428922fcdf9f2a2027df50a/src/main/java/com/jaoafa/mymaid4/event/Event_Jail.java#L110-L124

2022-03-16 04:20 UTC, book000 requested changes

2022-03-16 04:20 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_Jail.java
> +            Jail.hasWarned.put(uuid,true);
コード整形をお願いします

```suggestion
            Jail.hasWarned.put(uuid, true);
```

2022-03-16 04:20 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/EBan.java
> +                    MyMaidLibrary.teleportToParadise((Player) player);
この OfflinePlayer ってキャストしちゃって大丈夫か…？

2022-03-16 04:20 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/Jail.java
> +                    MyMaidLibrary.teleportToParadise((Player) player);
こちらもキャスト大丈夫かしら

2022-03-16 04:53 UTC, book000 approved these changes

2022-03-16 04:54 UTC, merged