Fix: SKKColor (#72)
jaoafa/MyMaid4 pull request #75
Opened 2021-03-28 01:44 UTC by yuuahp

ブランチ操作が下手なのは許してください...
SKKColorを直しました

2021-03-28 05:40 UTC, book000 commented
skkcolorのfixなのにselclickのremoveも混ざってない…？

2021-03-28 05:42 UTC, yuuahp commented
ブランチ分けミスです...

2021-03-28 05:43 UTC, book000 commented
スマホから見てる程度だからアレだけど、これは何をやっているの…？コンポーネント用にNamedTextColor?を使ってたやつをChatColorに戻している意味がよくわからん

2021-03-28 05:44 UTC, yuuahp commented
ChatColorにしたら治ったんです

2021-03-28 05:44 UTC, yuuahp commented
なぜか

2021-03-28 05:51 UTC, book000 commented
寧ろ、`Component.text("しかく", getPlayerColor(player))` が構文として正しくないかね…？
なんかアプローチを変えたほうがいい気がする。後で見るわ

2021-03-28 08:59 UTC, book000 commented
対応が完了しました。
**PaperMCを最新にアップデートする必要があります**。

以降のコメントで変更点を書きます

2021-03-28 09:05 UTC, book000 requested changes

2021-03-28 09:05 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/event/Event_SKKColor.java
>      }
```suggestion
    @EventHandler(priority = EventPriority.HIGHEST)
    public void onEvent_ChatSKK(AsyncChatEvent event) {
        Player player = event.getPlayer();
        ChatComposer composer = (_player, displayName, message) -> Component.translatable("chat.type.text", Component.text().append(
            Component.text("■", SKKColorManager.getPlayerColor(player)),
            displayName
        ), message);
        event.composer(composer);
    }
```

2021-03-28 09:05 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/SKKColorManager.java
> +        ChatColor.LIGHT_PURPLE);
不要です。
```suggestion
```

2021-03-28 09:05 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/SKKColorManager.java
>      }
```suggestion
    /**
     * プレイヤーの四角色を取得する
     *
     * @param player プレイヤー
     *
     * @return 四角色
     */
    public static NamedTextColor getPlayerColor(Player player) {
        int count = getVoteCount(player);
        return TextColorList.get(calculateRank(count));
    }
```

2021-03-28 09:05 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/SKKColorManager.java
完全に要らなさそうです

```suggestion
```

2021-03-28 09:05 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/SKKColorManager.java
> +                Component.text("■").color(getPlayerTextColor(player)),
戻して構いません
```suggestion
                Component.text("■").color(getPlayerColor(player)),
```

2021-03-28 09:05 UTC, book000 commented on src/main/java/com/jaoafa/mymaid4/lib/SKKColorManager.java
> +                Component.text("■").color(getPlayerTextColor(player)),
戻して構いません。

```suggestion
                Component.text("■").color(getPlayerColor(player)),
```

2021-03-28 09:05 UTC, book000 commented
以上、よろしくお願いします。

2021-03-28 11:47 UTC, book000 commented
(マージしていい時にお知らせください:heart:)

2021-03-28 11:48 UTC, yuuahp commented
マージして大丈夫です❤

2021-03-28 11:51 UTC, book000 approved these changes

2021-03-28 15:28 UTC, book000 commented
なんか…ビルドに失敗してます…
https://github.com/jaoafa/MyMaid4/pull/75/checks?check_run_id=2212944167

2021-03-28 15:32 UTC, book000 commented
多分これコンフリクトした時の修正でミスったやつだな…PC落としてしまったので明日以降修正お願いしてもいいですか…

2021-03-29 05:02 UTC, book000 approved these changes

2021-03-29 05:03 UTC, book000 commented
多分これで直ったでしょう…

2021-03-29 05:07 UTC, merged